services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3308:3306"
    volumes:
      - ./e-todo.sql:/docker-entrypoint-initdb.d/e-todo.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 15s
      timeout: 15s
      retries: 10

  backend:
    build: ./backend
    container_name: etodo_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

